SELECT omt_as_numeric(null) AS fail_null;
SELECT omt_as_numeric('.') AS fail_dot;
SELECT omt_as_numeric('a123') AS fail_prefixed_letter;
SELECT omt_as_numeric('123a') AS ok_integer;
SELECT omt_as_numeric('foobar') AS fail_text;
SELECT omt_as_numeric('9999999999') AS ok_big_positive;
SELECT omt_as_numeric('-9999999999') AS ok_big_negative;
SELECT omt_as_numeric('123') AS ok_integer;
SELECT omt_as_numeric('123.456') AS ok_float;
SELECT omt_as_numeric('  123.456  ') AS ok_float_trim;
SELECT omt_as_numeric('456.789e2') AS ok_e_notation;
